extends:
  - 'eslint:recommended'
  - '@typescript-eslint/recommended'
  - 'prettier'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module

env:
  node: true
  es6: true

rules:
  '@typescript-eslint/no-unused-vars': 'warn'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-explicit-any': 'warn'
