/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IncomeSurveyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllResponses"
      | "getAllStatistics"
      | "getDecryptedStatistics"
      | "getDevelopmentStatistics"
      | "getIncomeRange"
      | "getMyEncryptedIncomeRange"
      | "getParticipantAtIndex"
      | "getRange1Count"
      | "getRange2Count"
      | "getRange3Count"
      | "getTimestamp"
      | "hasDecryptionAccess"
      | "hasSurveyResponse"
      | "owner"
      | "protocolId"
      | "requestDecryptionAccess"
      | "submitPlainSurvey"
      | "submitSurvey"
      | "totalParticipants"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionAccessGranted"
      | "StatisticsUpdated"
      | "SurveySubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllResponses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDevelopmentStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIncomeRange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyEncryptedIncomeRange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRange1Count",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRange2Count",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRange3Count",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasDecryptionAccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSurveyResponse",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryptionAccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitPlainSurvey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSurvey",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalParticipants",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllResponses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDevelopmentStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIncomeRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyEncryptedIncomeRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRange1Count",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRange2Count",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRange3Count",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasDecryptionAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSurveyResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryptionAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPlainSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalParticipants",
    data: BytesLike
  ): Result;
}

export namespace DecryptionAccessGrantedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatisticsUpdatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveySubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IncomeSurvey extends BaseContract {
  connect(runner?: ContractRunner | null): IncomeSurvey;
  waitForDeployment(): Promise<this>;

  interface: IncomeSurveyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllResponses: TypedContractMethod<
    [],
    [[string, bigint] & { incomeRange: string; time: bigint }],
    "view"
  >;

  getAllStatistics: TypedContractMethod<
    [],
    [
      [string, string, string] & {
        range1Count: string;
        range2Count: string;
        range3Count: string;
      }
    ],
    "view"
  >;

  getDecryptedStatistics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        range1Count: bigint;
        range2Count: bigint;
        range3Count: bigint;
      }
    ],
    "view"
  >;

  getDevelopmentStatistics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        range1Count: bigint;
        range2Count: bigint;
        range3Count: bigint;
      }
    ],
    "view"
  >;

  getIncomeRange: TypedContractMethod<[], [string], "view">;

  getMyEncryptedIncomeRange: TypedContractMethod<[], [string], "view">;

  getParticipantAtIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getRange1Count: TypedContractMethod<[], [string], "view">;

  getRange2Count: TypedContractMethod<[], [string], "view">;

  getRange3Count: TypedContractMethod<[], [string], "view">;

  getTimestamp: TypedContractMethod<[], [bigint], "view">;

  hasDecryptionAccess: TypedContractMethod<[], [boolean], "view">;

  hasSurveyResponse: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestDecryptionAccess: TypedContractMethod<[], [void], "nonpayable">;

  submitPlainSurvey: TypedContractMethod<
    [_incomeRange: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitSurvey: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  totalParticipants: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllResponses"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { incomeRange: string; time: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllStatistics"
  ): TypedContractMethod<
    [],
    [
      [string, string, string] & {
        range1Count: string;
        range2Count: string;
        range3Count: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecryptedStatistics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        range1Count: bigint;
        range2Count: bigint;
        range3Count: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDevelopmentStatistics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        range1Count: bigint;
        range2Count: bigint;
        range3Count: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIncomeRange"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyEncryptedIncomeRange"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getParticipantAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRange1Count"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRange2Count"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRange3Count"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasDecryptionAccess"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasSurveyResponse"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestDecryptionAccess"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitPlainSurvey"
  ): TypedContractMethod<[_incomeRange: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitSurvey"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalParticipants"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DecryptionAccessGranted"
  ): TypedContractEvent<
    DecryptionAccessGrantedEvent.InputTuple,
    DecryptionAccessGrantedEvent.OutputTuple,
    DecryptionAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "StatisticsUpdated"
  ): TypedContractEvent<
    StatisticsUpdatedEvent.InputTuple,
    StatisticsUpdatedEvent.OutputTuple,
    StatisticsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SurveySubmitted"
  ): TypedContractEvent<
    SurveySubmittedEvent.InputTuple,
    SurveySubmittedEvent.OutputTuple,
    SurveySubmittedEvent.OutputObject
  >;

  filters: {
    "DecryptionAccessGranted(address,uint256)": TypedContractEvent<
      DecryptionAccessGrantedEvent.InputTuple,
      DecryptionAccessGrantedEvent.OutputTuple,
      DecryptionAccessGrantedEvent.OutputObject
    >;
    DecryptionAccessGranted: TypedContractEvent<
      DecryptionAccessGrantedEvent.InputTuple,
      DecryptionAccessGrantedEvent.OutputTuple,
      DecryptionAccessGrantedEvent.OutputObject
    >;

    "StatisticsUpdated(uint256)": TypedContractEvent<
      StatisticsUpdatedEvent.InputTuple,
      StatisticsUpdatedEvent.OutputTuple,
      StatisticsUpdatedEvent.OutputObject
    >;
    StatisticsUpdated: TypedContractEvent<
      StatisticsUpdatedEvent.InputTuple,
      StatisticsUpdatedEvent.OutputTuple,
      StatisticsUpdatedEvent.OutputObject
    >;

    "SurveySubmitted(address,uint256)": TypedContractEvent<
      SurveySubmittedEvent.InputTuple,
      SurveySubmittedEvent.OutputTuple,
      SurveySubmittedEvent.OutputObject
    >;
    SurveySubmitted: TypedContractEvent<
      SurveySubmittedEvent.InputTuple,
      SurveySubmittedEvent.OutputTuple,
      SurveySubmittedEvent.OutputObject
    >;
  };
}
