/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IncomeSurvey } from "./IncomeSurvey";
export type { IncomeSurveySepolia } from "./IncomeSurveySepolia";
export type { IncomeSurveySimple } from "./IncomeSurveySimple";
