/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IncomeSurvey__factory } from "./IncomeSurvey__factory";
export { IncomeSurveySepolia__factory } from "./IncomeSurveySepolia__factory";
export { IncomeSurveySimple__factory } from "./IncomeSurveySimple__factory";
